
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.quickscope"
require "user.colorizer"
require "user.zen-mode"
require "user.neoscroll"
require "user.todo-comments"
require "user.bookmark"
require "user.symbol-outline"
require "user.session-manager"
require "user.notify"
require "user.ts-context"
require "user.registers"
require "user.functions"
require "user.gps"

vim.cmd[[
let g:vimspector_enable_mappings = 'HUMAN'
]]
